# Whether to format it.  
# master formatting will delete rocksdb metadata  
# Worker formatting will delete the data directory.  
format_master = false  
format_worker = false  
  
# master configuration  
[master]  
meta_dir = "testing/meta"  
log = { level = "info", log_dir = "stdout", file_name = "master.log" }  
  
# TTL (Time-To-Live) configuration  
ttl_checker_interval = "1h"  
ttl_checker_retry_attempts = 3  
ttl_bucket_interval = "1h"  
ttl_max_retry_duration = "30m"  
ttl_retry_interval = "5s"  
  
# masta ha raft configuration.  
[journal]  
journal_addrs = [  
    {id = 1, hostname = "curvine-master", port = 8996}  # Updated hostname  
]  
journal_dir = "testing/journal"  
  
# Worker configuration  
[worker]  
dir_reserved = "0"  
data_dir = [  
    "[DISK]testing/data",  
]  
log = { level = "info", log_dir = "stdout", file_name = "worker.log" }  
enable_s3_gateway = true  
  
# Customer service configuration.  
[client]  
master_addrs = [  
    { hostname = "curvine-master", port = 8995 }  # Updated hostname  
]  
  
# fuse configuration  
[fuse]  
  
# The log configuration of the customer service side  
[log]  
level = "info"  
log_dir = "stdout"  
file_name = "curvine.log"  
  
# S3 Object Gateway configuration  
[s3_gateway]  
listen = "0.0.0.0:9900"  
region = "us-east-1"  
put_temp_dir = "/tmp/curvine-temp"  
put_memory_buffer_threshold = 1048576  
put_max_memory_buffer = 16777216  
get_chunk_size_mb = 1.0  
  
# Storage configuration with S3 backend  
[storage]  
ufs_type = "opendal-s3"  
s3_endpoint = "http://curvine-minio:9000"  
s3_region_name = "us-east-1"  # Added region  
s3_bucket = "thuongld"  
s3_access_key = "minioadmin"  
s3_secret_key = "minioadmin"